### ISSUE TITLE
SQL30081N ERROR

### ISSUE THREAD

**Issue by zekuraz** [ibmdb/vscode-extension#11]
I have been having issues with the extension. I want to create a new connection but i keep getting this error.

Test failed: Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "XXX.XXX.XXX.XXX".  Communication function detecting the error: "selectForRecvTimeout".  Protocol specific error code(s): "115", "*", "*".  SQLSTATE=08001

Version : 1.42.1
Validation : c47d83b293181d9be64f27ff093689e8e7aed054
Date : 2020-02-11T14:50:36.977Z
Électron : 6.1.6
Chrome : 76.0.3809.146
Node.js : 12.4.0
V8 : 7.6.303.31-electron.0
OS : Linux x64 4.15.0-76-generic

**Comment by akhilravuri1** [comment]
Hi @zekuraz 
Please restart the server and try to connect.
Even after if you are facing this issue please take db2trc and share that files.

Thanks,
Akhil

**Comment by WBSpmichal** [comment]
I am also having this issue, though some of the details of the error message are different

[IBM][CLI Driver] SQL30081N A communication error has been detected. 
Communication protocol being used: "TCP/IP". 
Communication API being used: "SOCKETS". 
Location where the error was detected: "10.100.0.102". 
Communication function detecting the error: "recv". 
Protocol specific error code(s): "*", "*", "0". 
SQLSTATE=08001

I am not familiar with how the ibm-i is setup. Where exactly do I run the db2trc in ibm-i? Is the CLI an extra component that has to be installed on the ibm-i?

**Comment by bimalkjha** [comment]
@WBSpmichal I hope you have not installed this extension on IBM-i but on some distributed platform. Please confirm.
To use db2connect extension to connect to AS400 server, make sure server has enabled the DRDA port and you use the DRDA port in connection string.
This error is not a bug in vscode-extension but it points out that client is unable to connect to AS400 server using the supplied connection string. Please verify your connection string and then try. Thanks.

**Comment by WBSpmichal** [comment]
I am trying to install the extension on my windows 11 work PC, not the ibm-i. sorry for the confusion. 

I am not the administrator of the ibm-i, so I am unsure of a lot of things regarding how it's set up. Also, I was not using a connection string but trying to connect manually using the server name supplied by running the WRKRDBDIRE in ibm-i, and then finding the port using netstat. 

there is another program, (websmart) we use that also has a connection to DB2 and is able to run queries, and I tried using the connection info from that, neither have worked so far.

when running netstat for ipv4 connections, I see there is a DRDA port that says it's listening
      *                *          drda       048:53:29  Listen 
     
but I don't know what what that means. 

Is there a guide to creating / generating a connection strings?

**Comment by bimalkjha** [comment]
@WBSpmichal You need to contact your IBM-i sysadmin and get the correct connection string with DRDA port. Without permission from sysadmin, you may not have the right info for connection.

Note that AS400 database support different kind of connection mechanism. IBM i Access uses different protocol and port for connection and same will not work for db2connect extension. I also do not have much info about AS400 administration. We are db2connect expert. 

Since, you know the drda port is listening, use the same port in connection string along with database name, hostname, userid and password. I can't help you get correct connection string from AS400 server. As long as you are getting SQL30081N using vscode extension, your connection string is incorrect. Thanks.
