### ISSUE TITLE
DB2 connect license file installed, but connection still fails

### ISSUE THREAD

**Issue by GerMFHub** [ibmdb/vscode-extension#35]
- Platform:
- vscode Version: 1.60.2
- Is node.js and npm installed: yes
- node.js and npm Version: 6.14.15
- Take a screen shot of VScode(Help->About) information and paste it:

Steps to Reproduce:

1. Db2 for z/os connection license file installed. It successfully uploaded by the plugin into .vscode\extensions\ibm.db2connect-2.3.0\node_modules\ibm_db\installer\clidriver\license, however connection fails with:
Connection to database failed: Error: [IBM][CLI Driver] SQL1598N An attempt to connect to the database server failed because of a licensing problem. SQLSTATE=42968

Same license is used to connect db2 via VS Code Db2 Developer Extension and  works fine

**Comment by GerMFHub** [comment]
tried to install older version of extension and now it's totally unusable. Getting:
command 'extension.Db2AddLicense' not found
command 'extension.Db2ExecuteFile' not found
 etc. basically all Db2 Connect command icons are not working
 
![image](https://user-images.githubusercontent.com/41899904/136058145-a81dc01c-3d50-466f-9c45-eb76a0f8d165.png)

**Comment by amukherjee28** [comment]
@GerMFHub 

There are two parts of the issues that you have faced.

1. Although License file is added if it continues to throw SQL1598N (Failed due to License), it is because of two reasons. Firstly the license file that is added is not in compliance with the version of DB2 Installed. So you may have to install the License for the proper version. Secondly I License file is added in incorrect location and it is not being read. (Although this we can rule out here as the license is added by the tool in the proper location)

So for the first issue even after adding the license file is the issue continues you may have to consider checking the version of license added and the version of DB2 installed.

2. The second issue that you are facing where none of the DB2 related commands are working in the for the vscode plugin.
You might have to check if the installation is active or not. Also consider using the option rebuild native module and check that the plugin updated to the latest and should fix the issue.

Thanks.

**Comment by bimalkjha** [comment]
@GerMFHub Please let us know if you are still facing this issue. We can relook into it. Thanks.

**Comment by GerMFHub** [comment]
Hi, 
Db2 connect driver version used as it same which is used to connect db2 via DB2 Data studio or connecting to Db2 via z/os Unix shell. And it works as intended connecting using those two options. Db2 server version is V12R1M505. Can you point me out which db2 connect driver version would contain appropriate driver version that is would be compatible with VS Code plugin?

**Comment by amukherjee28** [comment]
@GerMFHub
Currently VS code plugin in using db2_v115m5fp5 clidriver version for connection to DB2 Databases.

This driver get installed along with the plugin and is responsible for making all the database connection. For connecting to DB2 on ZOS you would require a license for the same version (db2_V115m5fp5).

Thanks

**Comment by GerMFHub** [comment]
downloaded db2 license which is currently available in z/os uss and it's used in connection thru uss to target db2 on lpar. But this is still fails. Any ideas on this?

**Comment by bimalkjha** [comment]
@GerMFHub What is the name of your license file? It should be db2con*.lic file and should be copied under clidriver/license directory. 
VS Code Db2 Developer Extension uses JDBC license file as a *.jar file which is not applicable for this extension. We need ODBC license file for this extension. Please follow the instructions as documented here: https://github.com/ibmdb/node-ibm_db#for-zos-and-iseries-connectivity-and-sql1598n-error
Thanks.
