### ISSUE TITLE
Extensions fails on MacOS

### ISSUE THREAD

**Issue by friguzzi** [ibmdb/vscode-extension#9]
I got this error
```
Failed to rebuild native modules, please reach out to our git page for help
```
on MacOS 10.15.3 with node js and npm installed

**Comment by akhilravuri1** [comment]
Hi @friguzzi 

vscode version ?

and try to run node --version and npm --version in your vscode terminal and paste the output.

Thanks,
Akhil

**Comment by friguzzi** [comment]
vscode version 14.1
node 12.6.0
npm 6.9.0

**Comment by akhilravuri1** [comment]
Hi @friguzzi 

Looks like your vscode version is not correct?

Please take screenshots and paste them.

To Find vscode Version:-

![image](https://user-images.githubusercontent.com/32290825/74025708-8e6dbf80-49ca-11ea-8d71-72ed1bc7cb67.png)
please click ABOUT in the Help options.
And Take a screenshot like this..
![image](https://user-images.githubusercontent.com/32290825/74025834-d5f44b80-49ca-11ea-9c11-065683e1176d.png)

Now to find Node Js and npm version from vscode terminal:-(please paste the screen shots)
1) click Terminal and select New terminal
![image](https://user-images.githubusercontent.com/32290825/74025966-21a6f500-49cb-11ea-870a-2570317a24de.png)

2) Terminal opens at the lower part of vscode--
![image](https://user-images.githubusercontent.com/32290825/74026025-41d6b400-49cb-11ea-93f2-02986ee752d1.png)

3) Now type ```node --version``` and ```npm --version``` in that terminal and paste me the screenshots.
![image](https://user-images.githubusercontent.com/32290825/74026146-882c1300-49cb-11ea-86d9-35e37e8f447b.png)


Thanks,
Akhil

**Comment by friguzzi** [comment]
I upgraded vscode, node and npm but still no luck
Here are the screenshots

![image](https://user-images.githubusercontent.com/9638148/74027608-ccf28280-49a8-11ea-91e7-9aa47a6fb3d9.png)
![image](https://user-images.githubusercontent.com/9638148/74027717-fdd2b780-49a8-11ea-9c72-82890511aa7b.png)

**Comment by friguzzi** [comment]
Can it be because I have node and npm installed also through brew?

**Comment by akhilravuri1** [comment]
Hi @friguzzi 

Currently I am out of station. So I can’t test whether it is because of brew or because of electron version. I will check this on Monday.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @friguzzi 

Mostly this issue can be because of proxy. Security not allowing the node js connections to download the clidriver from the internet.
If it is not because of prox please follow the below steps:-

Uninstall the extension and go to extension folder in .vscode in mac this .vscode folder is hidden(Ex: path for windows C:\Users\rakhil.vscode\extensions) delete ibm.db2connect-win-1.1.0 floder and try to install the extension.

After installation when you click Db2: Connect it tries to build native modules so at that time click the new terminal and go to the Output tab and select Db2Connect in that dropdown.

![image](https://user-images.githubusercontent.com/32290825/74148992-b4929a00-4c2c-11ea-946e-641bc8074ac2.png)

If you are facing issues please paste that log.

Thanks,
Akhil

**Comment by friguzzi** [comment]
The problem was that I didn't have the Apple Command Line tools for Xcode.
Installing them solved the problem. You should insert it into the requirements.
